### PR TITLE
v2 with release and docs

### PR DESCRIPTION
**Pull request by keevan**
- docs: update readme with instructions for the new version of workflows
- feat: add option to trigger optional release, if the token is provided

### CODE REVIEW

**Comment by keevan** [comment]
FYI I refactored the README to reflect new expected usage.

This should be merged after the release check is confirmed working and triggering as expected.

https://github.com/catalyst/catalyst-moodle-workflows/blob/9ee004e7ded8bcb5e5ee0c90b6567293768ef011/README.md

**Comment by danmarsden** [comment]
is there something in there that prevents the release process running on a pull_request call? - and only triggering on a "push" ? - we don't want a PR to be able to trigger the release process.

**Comment by keevan** [comment]
> is there something in there that prevents the release process running on a pull_request call? - and only triggering on a "push" ? - we don't want a PR to be able to trigger the release process.

Good question. The checks are here: 
https://github.com/catalyst/catalyst-moodle-workflows/blob/9ee004e7ded8bcb5e5ee0c90b6567293768ef011/.github/workflows/ci.yml

https://github.com/catalyst/catalyst-moodle-workflows/blob/9ee004e7ded8bcb5e5ee0c90b6567293768ef011/.github/workflows/ci.yml#L48-L65

This is currently set in the `ci.yml` reusable workflow, and is currently in a state where we're monitoring the conditions that would be applied. If those conditions are good, then it should be okay to enable this.

The one concern I had, however, was whether or not a workflow was going to run in a non-fork PR where the workflow itself was changed. I think there's actually nothing preventing this - should it happen at the moment.

**Comment by cameron1729** [comment]
Thanks for going through all this with me Kevin, I think the documentation is in pretty great, thanks for making some changes to fill some gaps as we discussed.

I was able to use the documentation to add a reusable workflow to an existing plugin. Great stuff. I'll merge this one.

**Pull request merged**
